version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - absjoin
  - adcs
  - colorama
  - COMXX
  - CREAD
  - DGRAM
  - DRDY
  - DUMBASS
  - ECONNRESET
  - espdevice
  - Espressif
  - esptool
  - essid
  - figsize
  - getch
  - IPPROTO
  - isconnected
  - kbhit
  - labjack
  - libqretprop
  - microcontroller
  - microcontrollers
  - micropython
  - Modbus
  - mpremote
  - Nikhil
  - numpy
  - osdebug
  - OSRAM
  - pinout
  - propnet
  - propteambestteam
  - PSRAM
  - pyproject
  - pyqtgraph
  - QRET
  - qretprop
  - qretproptools
  - QSPI
  - REUSEADDR
  - rreg
  - rrxx
  - showlegend
  - skiprows
  - SPIRAM
  - SREAD
  - ssdp
  - STRM
  - teststand
  - uasyncio
  - USBC
  - VREF
  - webrepl
  - WLAN
  - WREG
  - xaxes
  - yaxes
  - ylim
ignoreWords: []
import: []
