version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - absjoin
  - COMXX
  - DGRAM
  - DUMBASS
  - ECONNRESET
  - espdevice
  - Espressif
  - esptool
  - essid
  - figsize
  - getch
  - IPPROTO
  - isconnected
  - kbhit
  - labjack
  - libqretprop
  - microcontroller
  - microcontrollers
  - micropython
  - Modbus
  - mpremote
  - Nikhil
  - osdebug
  - OSRAM
  - pinout
  - PSRAM
  - pyproject
  - pyqtgraph
  - QRET
  - qretprop
  - qretproptools
  - QSPI
  - REUSEADDR
  - showlegend
  - skiprows
  - SPIRAM
  - ssdp
  - STRM
  - teststand
  - uasyncio
  - USBC
  - webrepl
  - WLAN
  - xaxes
  - yaxes
  - ylim
ignoreWords: []
import: []
